name: surface-roughness
channels: !!python/tuple
  - anaconda
  - nodefaults
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - pandas
  - ipykernel
  - jupyter
  - dask
  - distributed
  - scikit-learn
  - opencv
  - seaborn
  - tensorflow>=2.1

  - pip:
    - pathos
    - joblib
    - requests
    - statsmodels
    - flatten_dict
    - functional-pipeline
    - "--editable=."
